### PR TITLE
Fix Powerflow issues

### LINKED ISSUE #782: Power flow case doesn't handle storage correctly
When using PSID with battery, the battery isn't being correctly handled in the power flow

### PR DESCRIPTION
**Pull request by rodrigomha**
The following code closes #782 by allowing all StaticInjection to be used in PV Buses. In addition, it allows to split the power based on the `base_power` if multiple devices are connected in the same PV or REF bus.

### CODE REVIEW

File: src/utils/power_flow.jl [hunk 1]
```diff
@@ -142,19 +142,20 @@ function _write_pf_sol!(sys::System, nl_result)
...
         elseif bus.bustype == BusTypes.PV
             Q_gen = result[2 * ix - 1]
             θ = result[2 * ix]
-            injection_components = get_components(Generator, sys, x -> get_available(x))
-            devices = [d for d in injection_components if d.bus == bus]
-            if length(devices) == 1
-                generator = devices[1]
-                gen_basepower = get_base_power(generator)
-                set_reactive_power!(generator, Q_gen)
+            injection = get_components(StaticInjection, sys, x -> get_available(x))
```
Comment (jd-lara) [inline src/utils/power_flow.jl:154]: we can make a single call here that filters in the getter function 

```suggestion
            injection = get_components(StaticInjection, sys, x -> get_available(x) // x.bus == bus && !isa(x, ElectricLoad) )
```

**Review by jd-lara — CHANGES_REQUESTED** [review]
We need to add an entry to the power flow docs to document this behavior

File: src/utils/power_flow.jl [hunk 2]
```diff
@@ -142,19 +142,20 @@ function _write_pf_sol!(sys::System, nl_result)
             Q_gen = result[2 * ix]
             injection = get_components(StaticInjection, sys, x -> get_available(x))
```
Comment (jd-lara) [inline src/utils/power_flow.jl:143]: Apply the same change here please.

**Review by jd-lara — APPROVED** [review]
