### PR TITLE
Fix ThermalStandard must_run in tabular data parser

### LINKED ISSUE #981: TableDataParaser not catching must run from csv file
Is not reading must run from the csv file when creating `SystemTableData`

```julia
 return ThermalMultiStart(;
        name = get_name(thermal_gen),
        available = get_available(thermal_gen),
        status = get_status(thermal_gen),
        bus = get_bus(thermal_gen),
        active_power = get_active_power(thermal_gen),
        reactive_power = get_reactive_power(thermal_gen),
        rating = get_rating(thermal_gen),
        prime_mover = get_prime_mover(thermal_gen),
        fuel = get_fuel(thermal_gen),
        active_power_limits = get_active_power_limits(thermal_gen),
        reactive_power_limits = get_reactive_power_limits(thermal_gen),
        ramp_limits = get_ramp_limits(thermal_gen),
        power_trajectory = power_trajectory,
        time_limits = get_time_limits(thermal_gen),
        start_time_limits = startup_timelimits,
        start_types = start_types,
        operation_cost = op_cost,
        base_power = get_base_power(thermal_gen),
        time_at_status = get_time_at_status(thermal_gen),
        must_run = gen.must_run,
    )
end
```

### PR DESCRIPTION
**Pull request by scdhulipala**
Thanks for opening a PR to PowerSystems.jl, please take note of the following when making a PR: 

Check the [contributor guidelines](https://nrel-siip.github.io/PowerSystems.jl/stable/code_base_developer_guide/developer/)

1. Fix tabular data parser to parse _must_run_  for **ThermalStandard**
2. [Issue Fix](https://github.com/NREL-SIIP/PowerSystems.jl/issues/981)

closes #981

### CODE REVIEW

File: src/parsers/power_system_table_data.jl [hunk 1]
```diff
@@ -1020,6 +1020,7 @@ function make_thermal_generator(data::PowerSystemTableData, gen, cost_colnames,
         time_limits = timelimits,
         operation_cost = op_cost,
         base_power = base_power,
+        must_run = gen.must_run,
```
Comment (jd-lara) [inline src/parsers/power_system_table_data.jl:1023]: where is the must run info coming from?

Comment (scdhulipala) [reply src/parsers/power_system_table_data.jl:1023]: It is defined in power_system_structs.json and the user_descriptors.yml of the data, so the data would come from gen.csv. I'm not sure if that is the answer you're looking for.

Comment (jd-lara) [reply src/parsers/power_system_table_data.jl:1023]: But that value isn't been read and passed to the `ThermalStandard` call.

Comment (scdhulipala) [reply src/parsers/power_system_table_data.jl:1023]: Yeah, gen has a field must_run because it is defined in both user_descriptors and power_system_inputs.

Comment (jd-lara) [reply src/parsers/power_system_table_data.jl:1023]: Yes, that value is read from the CSV into the gen dict but you aren't reading it from that dict. Did you test this?

Comment (scdhulipala) [reply src/parsers/power_system_table_data.jl]: I'm running some more tests now with Pedro. I made this a draft for now. I will open a PR once I get the go ahead from Pedro.

Comment (scdhulipala) [reply src/parsers/power_system_table_data.jl]: I tested this on Pedro's ERCOT test data. This does what it is supposed to in general but will fail due to CSV data parsing. For instance, I printed gen.must_run for his data for debugging purposes and sometimes Bool is read as an InlineString.
gen_must_run = false
gen_must_run = InlineStrings.String7("False")

Comment (jd-lara) [reply src/parsers/power_system_table_data.jl]: Why not fix it in this PR?

**Comment by jd-lara** [comment]
Using parse is dangerous during runtime applications. It's better to employ a string comparison

**Comment by scdhulipala** [comment]
> Using parse is dangerous during runtime applications. It's better to employ a string comparison

The only reason I was usingparse was because must_run could be either a true/false (or) 1/0 which could be parsed as a String by the CSV parser (because of 'NA' values). Should I use stringcompariosn for all these cases then?
