### PR TITLE
Jd/minor fixes

### LINKED ISSUE #908: export `get_renewable_unit` for hybrid systems
Also review the other exports for the `HybridSystem`

### LINKED ISSUE #912: `base_power` is not typed to be `Float64` in constructors
This would have been helpful to debug a problem where an incorrect type in passed into `System(t)`, for example in the following:

```
┌ Warning: Code evaluation
│ There was an error of type 'LoadError' when running code 'auto_cell_4'
│ Details:
│ LoadError: MethodError: Cannot `convert` an object of type typeof(Main.__FRANKLIN_6111808.path) to an object of type Float64
│ Closest candidates are:
│   convert(::Type{T}, !Matched::ColorTypes.Gray24) where T<:Real at ~/.julia/packages/ColorTypes/1dGw6/src/conversions.jl:114
│   convert(::Type{T}, !Matched::ColorTypes.Gray) where T<:Real at ~/.julia/packages/ColorTypes/1dGw6/src/conversions.jl:113
│   convert(::Type{T}, !Matched::Base.TwicePrecision) where T<:Number at twiceprecision.jl:273
│   ...
│ Stacktrace:
│   [1] InfrastructureSystems.SystemUnitsSettings(base_value::Function, unit_system::InfrastructureSystems.UnitSystemModule.UnitSystem)
│     @ InfrastructureSystems ~/.julia/packages/InfrastructureSystems/vxA9a/src/internal.jl:11
│   [2] PowerSystems.System(data::InfrastructureSystems.SystemData, base_power::Function, internal::InfrastructureSystems.InfrastructureSystemsInternal; kwargs::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
│     @ PowerSystems ~/.julia/packages/PowerSystems/zVsmd/src/base.jl:97
│   [3] PowerSystems.System(data::InfrastructureSystems.SystemData, base_power::Function, internal::InfrastructureSystems.InfrastructureSystemsInternal)
│     @ PowerSystems ~/.julia/packages/PowerSystems/zVsmd/src/base.jl:94
│   [4] PowerSystems.System(data::InfrastructureSystems.SystemData, base_power::Function; internal::InfrastructureSystems.InfrastructureSystemsInternal, kwargs::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
│     @ PowerSystems ~/.julia/packages/PowerSystems/zVsmd/src/base.jl:108
│   [5] PowerSystems.System(data::InfrastructureSystems.SystemData, base_power::Function)
│     @ PowerSystems ~/.julia/packages/PowerSystems/zVsmd/src/base.jl:107
│   [6] PowerSystems.System(base_power::Function; kwargs::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
│     @ PowerSystems ~/.julia/packages/PowerSystems/zVsmd/src/base.jl:103
│   [7] PowerSystems.System(base_power::Function)
│     @ PowerSystems ~/.julia/packages/PowerSystems/zVsmd/src/base.jl:102
│
└ @ Xranklin ~/.julia/packages/Xranklin/rDvw7/src/context/code/notebook_code.jl:208
```

### PR DESCRIPTION
**Pull request by jd-lara**
Adds additional method to fix https://github.com/NREL-SIIP/PowerSimulations.jl/issues/876

closes #912
closes #908

### CODE REVIEW

File: src/base.jl [hunk 1]
```diff
@@ -91,20 +91,25 @@ struct System <: IS.InfrastructureSystemsType
     end
 end
 
-function System(data, base_power, internal; kwargs...)
+function System(data, base_power::Float64, internal; kwargs...)
```
Comment (daniel-thom) [inline src/base.jl:94]: Should we make this `base_power::Number` so that the user can use `System(100)`?

File: src/base.jl [hunk 2]
```diff
@@ -1491,6 +1496,26 @@ function get_buses(sys::System, bus_numbers::Set{Int})
     return buses
 end
 
+"""
+Return all the device types in the system. It does not return component types
+"""
+function get_existing_device_types(sys::System)
+    device_types = Vector{DataType}()
+    for component_type in keys(sys.data.components.data)
```
Comment (daniel-thom) [inline src/base.jl:1504]: Could you have a generator that is part of a HybridSystem that doesn't also exist as a regular component? If so, both of these functions should include `sys.data.masked_components`.

Comment (jd-lara) [reply src/base.jl:1504]: For the purpose of this function we don't want to return the masked components. In a way this function is meant to return device types available through calling `get_components`

Comment (daniel-thom) [reply src/base.jl:1504]: Perhaps include that note in the docstring so that people in the future don't wonder whether this is an oversight?

File: src/base.jl (hunk 1 above)
Comment (jd-lara) [reply src/base.jl:94]: ok

**Review by daniel-thom — APPROVED** [review]
